### ISSUE TITLE
Why it's not in melpa repo?

### ISSUE THREAD

**Issue by nedijahij** [manateelazycat/snails#34]
I am trying to install this package using use-package but I could not find it there. Will it ever be there anyttime soon because it's much easier to manage package using use-package. thanks

**Comment by manateelazycat** [comment]
I have played with Emacs for more than ten years, and I have written many Emacs plugins. Many people have suggested putting my Emacs plugin on MELPA.

My answer all the time is: NO

Write down the reason today, and if someone asks me again later, I can send this answer directly without having to answer it repeatedly:

Ten years ago, I promised my friend rgr to contribute org-w3m.el to the Emacs master branch, and it took me a lot of time. It was almost one night of coding, and the merged code was two months in a hurry.
Later, after listening to the suggestions of rgr, after putting all the plugins in EmacsWiki, the remaining ten years, my mailbox was bombed by various emacsers. This is the case for open source software. The creation time is very short, but the maintenance time is far away. Much longer than the time of creation, including multi-term.el, sdcv.el, auto-install.el, anything.el, auto-complete.el and other plug-ins that I often use, I have maintained it for more than ten years, although I am really happy to be able to help the emacsers around the world, but maintaining the plug-ins really takes my personal time
It is true that MELPA / Package.el is very convenient for users, and will let more people know about the plugin I wrote, but it also means that there will be hundreds of times users to raise issues and suggestions for me. I am a dislike to reject others People, if hundreds of times of users send issues and suggestions, I will certainly not sleep to perfect my plugin, that will definitely take up the time I spend with my family, and considering that, I hope that more time will make my family happy, and Not to make emacsers all over the world happier, although they are friendly and cute
Writing Emacs plugins and understanding the details of various plugins, I spent countless days and nights. Although MELPA allows 90% of Emacs users to automatically download and install (including dependencies) in one click, it has also achieved too much. Brain users, they will not search and research when they encounter problems, they will only complain, and eventually give up Emacs. Emacs is genetically not an out-of-the-box IDE, after all, you may not be able to program Elisp at first, but you must learn Elisp in the end Programming will make the Emacs Dragon Knife as easy as possible. Therefore, I don't want everyone to become a fool MELPA user, that will only lose the ability to solve Emacs problems, and finally push more users away Emacs, instead of embracing Emacs philosophy
I have now passed the period of proving my personal ability to the world. For the next few decades, I hope to spend more time learning new technologies and staying with my family, instead of endlessly tossing Emacs, tossing Emacs and Without learning advanced techniques, it is like an artisan who can only temper swords but has no time to practice swordsmanship.Emacs is always a tool for exploring curiosity. Emacs itself should not be the goal of learning
In addition to technology, I have a lot of my own opinions on the details of the product. I prefer to make some plug-ins that are out-of-the-box and elegant in detail, which is the feeling that is just enough, not too much and not too much. I do n’t like like Like traditional open source software developers, they make very rich Swiss Army Knives, even if many feature authors do n’t use it. If you use too many people, it will be difficult to tune. Finally, I write plugins that I do n’t even like. It ’s too boring. And to reject those who give constructive opinions, I myself can't bear it anymore, so my plugin is left for those emacser who have the same taste as me.
I have been very tired for the past ten years and always burden myself too much.

In the days to come, I want to live for my curiosity and personal habits. Keep it simple. I'm glad to like my work. I don't like my work. Welcome to continue exploring. The days are the simplest and happiest.
